services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
      - 51212:51212 # For Artillery load testing
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "5173:5173" # Or 5173 if you are using Vite
    stdin_open: true # Keeps the React terminal active
    tty: true
    depends_on:
      - backend
